return {
    {
        itemID = 1002,
        itemName = "Expensive Green",
        expansionLabel = "Cataclysm",
        locationLabel = "Deepholm 58.6,51.2",
        sourceText = "Stone Trogg",
        seenCount = 1,
        quantity = 1,
        value = 900000,
        marketValue = 500000,
        regionMarketValue = 700000,
        averageValue = 300000,
        tracked = true,
    },
    {
        itemID = 1001,
        itemName = "Observed Green",
        expansionLabel = "Classic",
        locationLabel = "Elwynn Forest 42.0,51.0",
        sourceText = "Test Gnoll",
        seenCount = 2,
        quantity = 3,
        value = 400000,
        marketValue = 500000,
        regionMarketValue = 700000,
        averageValue = 300000,
        tracked = false,
    },
}
